import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as fs from 'fs';
import * as path from 'path';

async function bootstrap() {
  // Read the certificate and key generated by mkcert
  const httpsOptions = {
      key: fs.readFileSync(path.resolve(__dirname, '../localhost-key.pem')),
      cert: fs.readFileSync(path.resolve(__dirname, '../localhost.pem')),
  };
  const app = await NestFactory.create(AppModule, {
      httpsOptions
  });
  app.setGlobalPrefix('api');
  app.enableCors();
  const port = process.env.PORT ?? 3009;
  await app.listen(port);
  console.log(`Movie App Server running on https://localhost:${port}/api`);
}
bootstrap();
